repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-toml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ".*fits|.*json|.*csv|.*inc"
    - id: trailing-whitespace
      exclude: ".*fits|.*json|.*csv|.*inc"

# - repo: https://github.com/pre-commit/pygrep-hooks
#   rev: v1.9.0
#   hooks:
#     - id: python-check-blanket-noqa
#     - id: python-check-mock-methods
#     - id: rst-directive-colons
#     - id: rst-inline-touching-normal
#     - id: text-unicode-replacement-char

# - repo: https://github.com/codespell-project/codespell
#   rev: v2.2.2
#   hooks:
#     - id: codespell
#       args: ["--write-changes"]
#       additional_dependencies:
#         - tomli

# - repo: https://github.com/asottile/pyupgrade
#   rev: 'v3.3.1'
#   hooks:
#     - id: pyupgrade
#       args: ["--py38-plus"]

# - repo: https://github.com/PyCQA/flake8
#   rev: 6.0.0
#   hooks:
#     - id: flake8
#       args: ["--count"]

# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.4
#   hooks:
#     - id: bandit
#       args: ["-c", "bandit.yaml"]
