repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-toml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ".*fits|.*json|.*csv|.*inc"
    - id: trailing-whitespace
      exclude: ".*fits|.*json|.*csv|.*inc"

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
    - id: python-check-blanket-noqa
    - id: python-check-mock-methods
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.170'
  hooks:
    - id: ruff
      args: ["--fix"]
      exclude: "jwst/extern|docs|scripts|jwst/associations|jwst/fits_generator"

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ["-c", "bandit.yaml"]
